### ISSUE TITLE
Missing component

### ISSUE THREAD

**Issue by myloran** [Spy-Shifty/BBSNetworkSystemExample#1]
I'm trying to get running your example, but i get missing component. I'm using unity 2018.0f2 and your latest BBSNetworkSystem.
![image](https://user-images.githubusercontent.com/3658316/43289777-ac693262-9134-11e8-9327-02c6eb445d4e.png)

**Comment by Spy-Shifty** [comment]
Hi,

are you missing the BBSNetworkSystem submodule? (Assets/BBSNetworkSystem @ a2828ab)
The missing component is the NetworkSyncComponent!

Github is a little bit buggy... you have to download it separatly

**Comment by myloran** [comment]
I needed to change instanceId to 1 in that component, now it's working
